### ISSUE TITLE
grad1 in train.py

### ISSUE THREAD

**Issue by P2333** [tml-epfl/understanding-fast-adv-training#1]
Hi Maksym,

Thank you for sharing the code. I think there may lack a definition of `grad1` (line 195) in `train.py` before it is referenced.

**Comment by max-andr** [comment]
Oh, can be, thanks for telling! 
Probably, I've refactored the code a bit uncarefully. I will fix it soon!

**Comment by P2333** [comment]
Cool! Thank you

**Comment by max-andr** [comment]
Fixed now (essentially i had to just use `grad` instead of the undefined `grad1`).

Thanks a lot for letting me know!
