### ISSUE TITLE
Request for ImageNet pre-trained models.

### ISSUE THREAD

**Issue by FeiiYin** [tml-epfl/understanding-fast-adv-training#4]
Hi, I'm really impressed with your excellent work.
Can you provide the pre-trained model's checkpoint on Dataset ImageNet?
Thanks!

**Comment by max-andr** [comment]
Hi,

Thanks for the interest in our work!

Unfortunately, I don't have the ImageNet models anymore. But you can train them from scratch using the code from ["Fast is better than free"](https://github.com/locuslab/fast_adversarial/tree/master/ImageNet) paper with the GradAlign regularizer.

I hope that helps.

Best,
Maksym
