### ISSUE TITLE
A bug in `eval.py`

### ISSUE THREAD

**Issue by cmhzc** [tml-epfl/understanding-fast-adv-training#5]
In line 51 of `eval.py`, when calling `get_model` you passed 6 arguments but it only takes 5. The `get_model` isn't able to take `args.n_hidden_fc` as an argument.

**Comment by max-andr** [comment]
Hi,

Thanks a lot for letting us know! Indeed, I missed that while I was refactoring the code :) now it's fixed in this commit: https://github.com/tml-epfl/understanding-fast-adv-training/commit/96d1a62a3b2c4bb32bd2ff59c6a1cc6f045bb284

Best,
Maksym
