### ISSUE TITLE
What is the `utils.nullcontext()`

### ISSUE THREAD

**Issue by CharlesJames13586** [tml-epfl/understanding-fast-adv-training#6]
The `utils.nullcontext()` appears in line 257 of the script `train.py.` But I can't find the definition. What is this?
I would appreciate it if you could get back to me!

**Comment by max-andr** [comment]
Hi,

Oops, sorry, I forgot to include this function after refactoring the code. It should be like this:

```python
from contextlib import contextmanager

@contextmanager
def nullcontext(enter_result=None):
    yield enter_result
```

Now it's fixed in https://github.com/tml-epfl/understanding-fast-adv-training/commit/ceed49440bfc35a676375b783eaba5940e583bcc. Thanks for letting us know about the problem!

Best,
Maksym

**Comment by CharlesJames13586** [comment]
Thank you and your work so much
